server:
  port: 8095 # Unique port for Team Service

spring:
  application:
    name: TEAM-SERVICE # Service ID for Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/team_db # For local running (will be overridden by Docker Compose)
    username: team_user
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically create/update tables based on entities
    show-sql: true # Log SQL statements
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL for local running
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost
    lease-renewal-interval-in-secs: 5
    lease-expiration-duration-in-secs: 10

# JWT Secret (must match Auth Service and Chat Service)
jwt:
  secret: aSecureRandomSecretKeyForJWTGenerationAndValidationThatIsLongEnoughAndComplex
  expiration: 3600000 # 1 hour in milliseconds
